export const S = {
  vi: {
    amount: 'Số tiền vay',
    rate: 'Lãi suất (%/năm)',
    term: 'Thời hạn vay (tháng)',
    method: 'Cách tính lãi',
    declining: 'Dư nợ giảm dần',
    annuity: 'Trả góp đều hàng tháng',
    flat: 'Lãi phẳng',
    first: 'Trả tháng đầu',
    totalInterest: 'Tổng tiền lãi',
    totalPayment: 'Tổng phải trả',
    schedule: 'Lịch trả nợ',
    cols: ['Kỳ', 'Tiền gốc', 'Tiền lãi', 'Tổng trả', 'Dư nợ còn lại'],
    errTerm: 'Thời hạn phải là số tháng nguyên từ 1 đến 600, số tiền vay lớn hơn 0.',
    example: { amount: '500.000.000', rate: '10' },
  },
  en: {
    amount: 'Loan amount',
    rate: 'Interest rate (% per year)',
    term: 'Term (months)',
    method: 'Interest method',
    declining: 'Declining balance',
    annuity: 'Fixed monthly payment',
    flat: 'Flat rate',
    first: 'First payment',
    totalInterest: 'Total interest',
    totalPayment: 'Total repayment',
    schedule: 'Repayment schedule',
    cols: ['Period', 'Principal', 'Interest', 'Payment', 'Balance'],
    errTerm: 'The term must be 1 to 600 whole months and the amount greater than 0.',
    example: { amount: '20,000', rate: '8' },
  },
};
export type LoanStrings = (typeof S)['vi'];
