export const S = {
  vi: {
    amount: 'Số tiền vay',
    rate: 'Lãi suất (%/năm)',
    term: 'Thời hạn vay (tháng)',
    method: 'Cách tính lãi',
    declining: 'Dư nợ giảm dần',
    annuity: 'Trả góp đều hàng tháng',
    flat: 'Lãi phẳng',
    first: 'Trả tháng đầu',
    totalInterest: 'Tổng tiền lãi',
    totalPayment: 'Tổng phải trả',
    schedule: 'Lịch trả nợ',
    cols: ['Kỳ', 'Tiền gốc', 'Tiền lãi', 'Tổng trả', 'Dư nợ còn lại'],
    errTerm: 'Thời hạn phải là số tháng nguyên từ 1 đến 600, số tiền vay lớn hơn 0. Vay 0 đồng thì khỏi cần tính, sướng nhất.',
    errInvalid: 'Ô này cần một con số hợp lệ, ví dụ 500.000.000. Nhập chữ thì máy tính cũng bối rối.',
    quipFree: 'Vay không lãi! Người cho vay thế này hiếm như chỗ đậu xe giờ cao điểm, giữ gìn nhé.',
    quips: [
      [0.05, 'Tiền lãi chỉ bằng {pct}% tiền vay. Món nợ này khá hiền, trả đều tay là xong.'],
      [0.15, 'Tiền lãi bằng {pct}% tiền vay. Có kế hoạch rõ ràng thì món nợ nào cũng có ngày về 0.'],
      [0.3, 'Tiền lãi bằng {pct}% tiền vay. Biết trước con số là đã đi trước món nợ một bước rồi.'],
      [0.6, 'Tiền lãi bằng {pct}% tiền vay. Thử so thêm vài mức lãi suất, biết đâu dư ra một chuyến du lịch.'],
      [1, 'Tiền lãi bằng {pct}% tiền vay. Kỳ hạn dài giúp mỗi tháng nhẹ hơn nhưng tổng lãi nặng hơn, cân nhắc nhé.'],
      [Infinity, 'Tiền lãi đã vượt cả tiền vay. Không sao, tính kỹ từ bây giờ là bạn đã làm đúng rồi.'],
    ] as [number, string][],
    example: { amount: '500.000.000', rate: '10' },
  },
  en: {
    amount: 'Loan amount',
    rate: 'Interest rate (% per year)',
    term: 'Term (months)',
    method: 'Interest method',
    declining: 'Declining balance',
    annuity: 'Fixed monthly payment',
    flat: 'Flat rate',
    first: 'First payment',
    totalInterest: 'Total interest',
    totalPayment: 'Total repayment',
    schedule: 'Repayment schedule',
    cols: ['Period', 'Principal', 'Interest', 'Payment', 'Balance'],
    errTerm: 'The term must be 1 to 600 whole months and the amount greater than 0. Borrowing nothing is the best deal, though.',
    errInvalid: 'This field needs a valid number, like 20,000. Letters confuse the calculator.',
    quipFree: 'An interest-free loan! Lenders like that are rarer than parking at rush hour. Keep them close.',
    quips: [
      [0.05, 'Interest is just {pct}% of the loan. A gentle debt, steady payments will see it off.'],
      [0.15, 'Interest is {pct}% of the loan. With a clear plan, every debt reaches zero someday.'],
      [0.3, 'Interest is {pct}% of the loan. Knowing the number already puts you one step ahead.'],
      [0.6, 'Interest is {pct}% of the loan. Comparing a few rates might fund a nice holiday.'],
      [1, 'Interest is {pct}% of the loan. Longer terms mean lighter months but more interest overall.'],
      [Infinity, 'The interest is more than the loan itself. Planning it out now is exactly the right move.'],
    ] as [number, string][],
    example: { amount: '20,000', rate: '8' },
  },
};
export type LoanStrings = (typeof S)['vi'];
