export const S = {
  vi: {
    start: 'Từ ngày',
    startTime: 'Từ giờ',
    end: 'Đến ngày',
    endTime: 'Đến giờ',
    includeEnd: 'Tính cả ngày cuối',
    includeEndOff: 'Đã nhập giờ nên tính chính xác theo giờ, không cần tính thêm ngày cuối.',
    days: 'Số ngày',
    exact: 'Chính xác',
    weeks: 'Số tuần',
    months: 'Tháng và ngày',
    weekdays: 'Ngày làm việc (thứ 2 đến thứ 6)',
    totalHours: 'Tổng số giờ',
    unitDay: 'ngày',
    unitDays: 'ngày',
    unitWeek: 'tuần',
    unitWeeks: 'tuần',
    unitMonth: 'tháng',
    unitMonths: 'tháng',
    unitHour: 'giờ',
    unitMinute: 'phút',
    countdown: 'Đếm ngược tới {when}',
    elapsed: 'Đã trôi qua kể từ {when}',
    errDate: 'Nhập hai ngày theo dạng dd/mm/yyyy, ví dụ 31/12/2026.',
    errTime: 'Giờ chưa đúng. Nhập kiểu 08:00 hoặc 17h30, hoặc để trống.',
    quips: [
      [1, 'Cùng một ngày. Khoảng cách ngắn hơn cả thời gian chờ thang máy giờ cao điểm.'],
      [2, 'Đúng 1 ngày. Ngủ một giấc là tới nơi.'],
      [7, 'Chưa tới một tuần, chưa kịp nhớ nhau đâu.'],
      [31, 'Vài tuần thôi, vừa đủ để hứa "tuần sau mình bắt đầu tập gym".'],
      [100, 'Hơn một tháng. Đủ để một cây rau muống ra hoa, và để bạn quên mật khẩu email.'],
      [366, 'Dưới một năm. Đủ thời gian để đổi kế hoạch năm mới khoảng ba lần.'],
      [3653, 'Vài năm liền. Đủ để điện thoại của bạn lỗi thời hai lượt.'],
      [Infinity, 'Hơn một thập kỷ. Xin chúc mừng sự kiên nhẫn phi thường.'],
    ] as [number, string][],
  },
  en: {
    start: 'Start date',
    startTime: 'Start time',
    end: 'End date',
    endTime: 'End time',
    includeEnd: 'Include end date',
    includeEndOff: 'With times entered the count is exact to the minute, so the end date is not added.',
    days: 'Days',
    exact: 'Exact',
    weeks: 'Weeks',
    months: 'Months and days',
    weekdays: 'Weekdays (Mon to Fri)',
    totalHours: 'Total hours',
    unitDay: 'day',
    unitDays: 'days',
    unitWeek: 'week',
    unitWeeks: 'weeks',
    unitMonth: 'month',
    unitMonths: 'months',
    unitHour: 'h',
    unitMinute: 'min',
    countdown: 'Counting down to {when}',
    elapsed: 'Time since {when}',
    errDate: 'Enter both dates as mm/dd/yyyy, for example 12/31/2026.',
    errTime: 'That time looks off. Use 08:00 or 17:30, or leave it empty.',
    quips: [
      [1, 'Same day. Shorter than waiting for the lift at rush hour.'],
      [2, 'Exactly one day. One good night of sleep and you are there.'],
      [7, 'Less than a week. Not even time to miss each other.'],
      [31, 'A few weeks. Just enough to say "I will start the gym next week".'],
      [100, 'Over a month. Long enough to forget your email password.'],
      [366, 'Under a year. Enough time to change your New Year plans about three times.'],
      [3653, 'A few years. Your phone will go out of date twice.'],
      [Infinity, 'More than a decade. Congratulations on your heroic patience.'],
    ] as [number, string][],
  },
};
export type DateDiffStrings = (typeof S)['vi'];
