export const S = {
  vi: {
    start: 'Từ ngày',
    end: 'Đến ngày',
    includeEnd: 'Tính cả ngày cuối',
    days: 'Số ngày',
    weeks: 'Số tuần',
    months: 'Tháng và ngày',
    weekdays: 'Ngày làm việc (thứ 2 đến thứ 6)',
    unitDay: 'ngày',
    unitDays: 'ngày',
    unitWeek: 'tuần',
    unitWeeks: 'tuần',
    unitMonth: 'tháng',
    unitMonths: 'tháng',
    errDate: 'Vui lòng chọn hai ngày hợp lệ.',
  },
  en: {
    start: 'Start date',
    end: 'End date',
    includeEnd: 'Include end date',
    days: 'Days',
    weeks: 'Weeks',
    months: 'Months and days',
    weekdays: 'Weekdays (Mon to Fri)',
    unitDay: 'day',
    unitDays: 'days',
    unitWeek: 'week',
    unitWeeks: 'weeks',
    unitMonth: 'month',
    unitMonths: 'months',
    errDate: 'Please pick two valid dates.',
  },
};
export type DateDiffStrings = (typeof S)['vi'];
