export const S = {
  vi: {
    amount: 'Số tiền gửi',
    rate: 'Lãi suất (%/năm)',
    term: 'Kỳ hạn (tháng)',
    method: 'Cách tính lãi',
    simple: 'Lãi cuối kỳ',
    monthly: 'Lãi nhập gốc hàng tháng',
    interest: 'Tiền lãi',
    total: 'Tổng nhận cuối kỳ',
    errTerm: 'Kỳ hạn phải là số tháng nguyên từ 1 đến 600. Gửi 0 tháng thì ngân hàng chưa kịp nhớ mặt bạn.',
    errInvalid: 'Ô này cần một con số hợp lệ, ví dụ 100.000.000. Chữ thì ngân hàng không tính lãi.',
    cupPrice: 35000,
    quipNoMoney: 'Gửi 0 đồng thì lãi cũng 0 đồng. Toán học công bằng lắm.',
    quipZeroRate: 'Lãi suất 0% thì tiền chỉ đi nghỉ mát chứ không đi làm. Nhập lãi suất để tiền đẻ ra tiền.',
    quipCrumbs: 'Tiền lãi chưa đủ một ly trà sữa (tính 35.000 đ/ly). Nhưng góp gió thì thành bão.',
    quips: [
      [0.01, 'Lãi đủ mua {cups} ly trà sữa (tính 35.000 đ/ly). Ít thôi, nhưng là tiền tự sinh ra.'],
      [0.05, 'Lãi đủ mua {cups} ly trà sữa (tính 35.000 đ/ly). Tiền đang chăm chỉ đi làm thay bạn.'],
      [0.15, 'Lãi đủ mua {cups} ly trà sữa (tính 35.000 đ/ly). Kiên nhẫn đúng là có quả ngọt, ít đường.'],
      [0.5, 'Lãi đủ mua {cups} ly trà sữa (tính 35.000 đ/ly). Con heo đất nhìn bạn đầy ngưỡng mộ.'],
      [1, 'Lãi đã hơn nửa tiền gốc, cỡ {cups} ly trà sữa (35.000 đ/ly). Gửi lâu nhớ đừng quên sổ ở đâu.'],
      [Infinity, 'Tiền lãi đã vượt cả tiền gốc. Lãi kép đúng là phép màu, chỉ cần kiên nhẫn rất, rất lâu.'],
    ] as [number, string][],
    example: { amount: '100.000.000', rate: '6' },
  },
  en: {
    amount: 'Deposit amount',
    rate: 'Interest rate (% per year)',
    term: 'Term (months)',
    method: 'Interest method',
    simple: 'Simple interest',
    monthly: 'Compounded monthly',
    interest: 'Interest earned',
    total: 'Total at maturity',
    errTerm: 'The term must be a whole number of months from 1 to 600. Zero months is just visiting the bank.',
    errInvalid: 'This field needs a valid number, like 10,000. Banks do not pay interest on words.',
    cupPrice: 5,
    quipNoMoney: 'Deposit 0, earn 0. Math is nothing if not fair.',
    quipZeroRate: 'At 0% your money is on vacation, not at work. Enter a rate to put it to work.',
    quipCrumbs: 'The interest does not cover one fancy coffee yet (at 5 a cup). Every big pile starts small.',
    quips: [
      [0.01, 'That interest buys about {cups} fancy coffees at 5 a cup. Small, but it made itself.'],
      [0.05, 'About {cups} fancy coffees at 5 a cup. Your money is working while you are not.'],
      [0.15, 'About {cups} fancy coffees at 5 a cup. Patience pays, literally.'],
      [0.5, 'About {cups} fancy coffees at 5 a cup. Your piggy bank is quietly impressed.'],
      [1, 'Interest is over half the deposit, about {cups} coffees at 5 a cup. Do not forget where you parked it.'],
      [Infinity, 'The interest beats the deposit itself. Compound interest is magic, it just takes a very long time.'],
    ] as [number, string][],
    example: { amount: '10,000', rate: '5' },
  },
};
export type SavingsStrings = (typeof S)['vi'];
