export const S = {
  vi: {
    price: 'Giá gốc',
    pct: 'Giảm (%)',
    extra: 'Giảm thêm (%)',
    final: 'Giá sau giảm',
    saved: 'Tiết kiệm',
    total: 'Tổng % giảm',
    errPct: 'Phần trăm giảm phải từ 0 đến 100. Giảm quá 100% thì shop phải trả tiền ngược cho bạn mất.',
    quips: [
      [0.000001, 'Giảm 0%: giá gốc khoác áo sale. Đừng để chữ SALE đỏ chót đánh lừa.'],
      [10, 'Giảm cho có lệ thôi. Đủ để vui, chưa đủ để khoe.'],
      [30, 'Giảm kha khá. Chưa phải deal của năm, nhưng chốt cũng không ai trách.'],
      [50, 'Giảm sâu rồi đó. Ví bạn bắt đầu thấy rung rinh.'],
      [80, 'Giảm hơn một nửa. Đây là lúc giỏ hàng tự dưng đầy lên mà không hiểu vì sao.'],
      [100, 'Giảm cực sâu. Mua thì mua, nhưng nhớ hỏi kỹ chuyện đổi trả nhé.'],
      [Infinity, 'Giảm 100%: miễn phí! Gặp ngoài đời thật thì chạy ngay, kẻo hết.'],
    ] as [number, string][],
    example: { price: '450.000', pct: '30' },
  },
  en: {
    price: 'Original price',
    pct: 'Discount (%)',
    extra: 'Extra discount (%)',
    final: 'Final price',
    saved: 'You save',
    total: 'Total discount',
    errPct: 'Discounts must be between 0 and 100. Any higher and the shop would be paying you.',
    quips: [
      [0.000001, '0% off: the original price wearing a SALE costume. Do not be fooled by the red sticker.'],
      [10, 'A token discount. Nice to have, not quite worth bragging about.'],
      [30, 'A decent deal. Not the bargain of the year, but nobody will judge you.'],
      [50, 'Now we are talking. Your wallet is starting to get excited.'],
      [80, 'More than half off. This is how carts fill up mysteriously.'],
      [100, 'A massive discount. Go for it, but check the return policy first.'],
      [Infinity, '100% off: it is free! If you see this in real life, run.'],
    ] as [number, string][],
    example: { price: '120', pct: '30' },
  },
};
export type DiscountStrings = (typeof S)['vi'];
