export const S = {
  vi: {
    birth: 'Ngày sinh',
    birthTime: 'Giờ sinh',
    ref: 'Tính đến ngày',
    refTime: 'Đến giờ',
    year: 'năm',
    years: 'năm',
    month: 'tháng',
    months: 'tháng',
    day: 'ngày',
    days: 'ngày',
    hour: 'giờ',
    minute: 'phút',
    totalDays: 'Tổng số ngày đã sống',
    next: 'Sinh nhật tiếp theo',
    daysLeft: 'Còn lại',
    today: 'Chính là hôm nay!',
    bornOn: 'Bạn sinh vào',
    heartbeats: 'Tim đã đập khoảng',
    sleep: 'Đã ngủ khoảng',
    tickerLive: 'Bạn đã có mặt trên Trái Đất được',
    tickerFixed: 'Tổng thời gian đã sống',
    footNoTime: 'Chưa có giờ sinh nên tính từ 00:00. Thêm giờ sinh để chính xác tới từng giây.',
    footUntil: 'Tính đến {time} ngày {date}.',
    errOrder: 'Ngày sinh nằm sau ngày cần tính? Chào nhà du hành thời gian! Bạn kiểm tra lại giúp nhé.',
    errDate: 'Nhập ngày theo dạng dd/mm/yyyy, ví dụ 15/08/1995.',
    errTime: 'Giờ chưa đúng. Nhập kiểu 07:30 hoặc 19h45, hoặc để trống cũng được.',
    quipBirthday: 'Chúc mừng sinh nhật! Hôm nay bạn được miễn rửa bát.',
    quips: [
      [1, 'Mới tí tuổi đã biết dùng máy tính tuổi, tương lai sáng lạn đây.'],
      [6, 'Tuổi này nhiệm vụ chính là ăn, ngủ và làm bố mẹ mất ngủ.'],
      [13, 'Tuổi hỏi "tại sao" khoảng 300 lần mỗi ngày. Bố mẹ xin được nghỉ phép.'],
      [18, 'Tuổi teen: biết hết mọi thứ trên đời, trừ bài tập về nhà.'],
      [25, 'Tuổi đẹp nhất để thức tới 2 giờ sáng mà hôm sau mặt vẫn tươi.'],
      [30, 'Chính thức vào mùa bị hỏi "bao giờ cưới" mỗi dịp Tết.'],
      [40, 'Tuổi mà đứng dậy khỏi ghế cũng phát ra âm thanh.'],
      [50, 'Bắt đầu chuyển sang uống nước ấm và bàn chuyện đau lưng.'],
      [60, 'Kinh nghiệm đầy mình, kính lão đầy túi.'],
      [80, 'Tuổi được mời phát biểu ở mọi đám cưới trong họ.'],
      [Infinity, 'Huyền thoại sống. Cho xin chữ ký với!'],
    ] as [number, string][],
  },
  en: {
    birth: 'Date of birth',
    birthTime: 'Time of birth',
    ref: 'Age at date',
    refTime: 'At time',
    year: 'year',
    years: 'years',
    month: 'month',
    months: 'months',
    day: 'day',
    days: 'days',
    hour: 'h',
    minute: 'min',
    totalDays: 'Total days lived',
    next: 'Next birthday',
    daysLeft: 'Days to go',
    today: 'It’s today!',
    bornOn: 'Born on a',
    heartbeats: 'Heartbeats, roughly',
    sleep: 'Time spent asleep, roughly',
    tickerLive: 'You have been on planet Earth for',
    tickerFixed: 'Total time lived',
    footNoTime: 'No time of birth yet, so counting from 00:00. Add it to get the exact second.',
    footUntil: 'Counted up to {time} on {date}.',
    errOrder: 'Born after the age-at date? Greetings, time traveller! Please check the dates.',
    errDate: 'Enter dates as mm/dd/yyyy, for example 08/15/1995.',
    errTime: 'That time looks off. Use 07:30 or 19:45, or leave it empty.',
    quipBirthday: 'Happy birthday! You are officially excused from doing the dishes today.',
    quips: [
      [1, 'Using an age calculator before your first birthday. Big things ahead.'],
      [6, 'Main job at this age: eat, sleep and keep the parents awake.'],
      [13, 'The "but why?" years. About 300 questions a day, give or take.'],
      [18, 'Teenager: knows everything, except where the homework went.'],
      [25, 'Peak age for staying up until 2 a.m. and still looking fresh.'],
      [30, 'Officially in the "so when are you getting married?" season.'],
      [40, 'The age when standing up from a chair comes with sound effects.'],
      [50, 'Warm water, early nights and strong opinions about back pain.'],
      [60, 'Full of wisdom, pockets full of reading glasses.'],
      [80, 'Invited to give a speech at every family wedding.'],
      [Infinity, 'A living legend. Can we have an autograph?'],
    ] as [number, string][],
  },
};
export type AgeStrings = (typeof S)['vi'];
