export const S = {
  vi: {
    birth: 'Ngày sinh',
    ref: 'Tính đến ngày',
    year: 'năm',
    years: 'năm',
    month: 'tháng',
    months: 'tháng',
    day: 'ngày',
    days: 'ngày',
    totalDays: 'Tổng số ngày đã sống',
    next: 'Sinh nhật tiếp theo',
    daysLeft: 'Còn lại',
    today: 'Hôm nay là sinh nhật!',
    bornOn: 'Bạn sinh vào',
    errOrder: 'Ngày sinh phải trước hoặc bằng ngày cần tính.',
    errDate: 'Vui lòng chọn ngày hợp lệ.',
  },
  en: {
    birth: 'Date of birth',
    ref: 'Age at date',
    year: 'year',
    years: 'years',
    month: 'month',
    months: 'months',
    day: 'day',
    days: 'days',
    totalDays: 'Total days lived',
    next: 'Next birthday',
    daysLeft: 'Days to go',
    today: 'It’s the birthday today!',
    bornOn: 'Born on a',
    errOrder: 'The date of birth must be on or before the age-at date.',
    errDate: 'Please pick a valid date.',
  },
};
export type AgeStrings = (typeof S)['vi'];
