export const S = {
  vi: {
    s2l: 'Dương sang Âm',
    l2s: 'Âm sang Dương',
    solar: 'Ngày dương lịch',
    lday: 'Ngày âm',
    lmonth: 'Tháng âm',
    lyear: 'Năm âm',
    leap: 'Tháng nhuận',
    leapLabel: 'nhuận',
    lunarFmt: 'Ngày {d} tháng {m}{leap} năm {y}',
    canChi: 'Can Chi',
    year: 'Năm',
    month: 'Tháng',
    day: 'Ngày',
    weekday: 'Thứ',
    errLunar: 'Ngày âm này không tồn tại (tháng thiếu chỉ có 29 ngày, hoặc năm này không có tháng nhuận đó).',
    errDate: 'Vui lòng nhập ngày hợp lệ.',
  },
  en: {
    s2l: 'Solar to Lunar',
    l2s: 'Lunar to Solar',
    solar: 'Solar date',
    lday: 'Lunar day',
    lmonth: 'Lunar month',
    lyear: 'Lunar year',
    leap: 'Leap month',
    leapLabel: ' (leap)',
    lunarFmt: 'Day {d}, month {m}{leap}, year {y}',
    canChi: 'Can Chi',
    year: 'Year',
    month: 'Month',
    day: 'Day',
    weekday: 'Weekday',
    errLunar: 'This lunar date does not exist (short months have 29 days, or the year has no such leap month).',
    errDate: 'Please enter a valid date.',
  },
};
export type LunarStrings = (typeof S)['vi'];
