export const S = {
  vi: {
    s2l: 'Dương sang Âm',
    l2s: 'Âm sang Dương',
    solar: 'Ngày dương lịch',
    time: 'Giờ',
    lday: 'Ngày âm',
    lmonth: 'Tháng âm',
    lyear: 'Năm âm',
    leap: 'Tháng nhuận',
    leapLabel: 'nhuận',
    lunarFmt: 'Ngày {d} tháng {m}{leap} năm {y}',
    canChi: 'Can Chi',
    year: 'Năm',
    month: 'Tháng',
    day: 'Ngày',
    hour: 'Giờ',
    weekday: 'Thứ',
    goodHours: 'Giờ hoàng đạo trong ngày',
    isGoodHour: 'Giờ {name} là giờ hoàng đạo. Chọn giờ thế này thì cứ yên tâm mà làm.',
    notGoodHour: 'Giờ {name} không phải giờ hoàng đạo. Nhưng làm việc tốt thì giờ nào cũng đẹp.',
    tetCountdown: 'Còn bao lâu nữa đến Tết {canChi}',
    tetFoot: 'Mùng 1 Tết rơi vào {date}.',
    errLunar: 'Ngày âm này không tồn tại (tháng thiếu chỉ có 29 ngày, hoặc năm này không có tháng nhuận đó).',
    errDate: 'Nhập ngày theo dạng dd/mm/yyyy, trong khoảng năm 1901 đến 2099.',
    errTime: 'Giờ chưa đúng. Nhập kiểu 07:30 hoặc 23h, hoặc để trống.',
    quipTet: 'Đang Tết mà vẫn mở máy tra lịch? Cất điện thoại, ra nhận lì xì đi!',
    quipFirst: 'Mùng 1 đầu tháng: ăn chay, đi chùa, và tuyệt đối chưa đòi nợ ai.',
    quipFull: 'Ngày rằm: trăng tròn, mâm cúng đầy, bụng cũng sắp đầy.',
    quipMidAutumn: 'Rằm tháng Tám: Trung thu rồi! Bánh nướng hay bánh dẻo đây?',
    quipGhost: 'Tháng 7 âm: tháng cô hồn. Giữ chặt ví và đừng nhặt tiền rơi ngoài đường.',
    quipYearEnd: 'Tháng Chạp rồi: dọn nhà, sắm Tết và chuẩn bị tinh thần bị hỏi lương.',
    quips: [
      'Ngày thường, nhưng biết ngày âm rồi thì gọi điện cho bà cũng có chuyện để nói.',
      'Âm lịch đã tra xong. Giờ thì bạn đã hiểu vì sao Tết mỗi năm một ngày khác.',
      'Một ngày bình yên. Không rằm, không mùng 1, cứ thế mà sống tốt.',
    ],
  },
  en: {
    s2l: 'Solar to Lunar',
    l2s: 'Lunar to Solar',
    solar: 'Solar date',
    time: 'Time',
    lday: 'Lunar day',
    lmonth: 'Lunar month',
    lyear: 'Lunar year',
    leap: 'Leap month',
    leapLabel: ' (leap)',
    lunarFmt: 'Day {d}, month {m}{leap}, year {y}',
    canChi: 'Can Chi',
    year: 'Year',
    month: 'Month',
    day: 'Day',
    hour: 'Hour',
    weekday: 'Weekday',
    goodHours: 'Auspicious (hoàng đạo) hours of the day',
    isGoodHour: 'The {name} hour is auspicious. Go ahead with confidence.',
    notGoodHour: 'The {name} hour is not an auspicious one. Then again, good deeds are on time whenever.',
    tetCountdown: 'Time left until Tết {canChi}',
    tetFoot: 'Lunar New Year’s Day falls on {date}.',
    errLunar: 'This lunar date does not exist (short months have 29 days, or the year has no such leap month).',
    errDate: 'Enter the date as mm/dd/yyyy, between 1901 and 2099.',
    errTime: 'That time looks off. Use 07:30 or 23:00, or leave it empty.',
    quipTet: 'Checking the calendar during Tết? Put the phone down and go collect your lucky money!',
    quipFirst: 'First day of the lunar month: temple visits, vegetarian food and no debt collecting.',
    quipFull: 'Full moon day: round moon, full offering tray, soon a full stomach.',
    quipMidAutumn: 'The 15th of the 8th month: Mid-Autumn Festival! Baked or sticky mooncake?',
    quipGhost: 'Lunar month 7, the ghost month. Hold on to your wallet and leave dropped money alone.',
    quipYearEnd: 'The last lunar month: time to clean the house and prepare for salary questions at Tết.',
    quips: [
      'An ordinary day. Still, now you have something to talk about with grandma.',
      'Done. Now you know why Tết lands on a different day every year.',
      'A quiet day. No full moon, no first day, just live well.',
    ],
  },
};
export type LunarStrings = (typeof S)['vi'];
