export const S = {
  vi: {
    bank: 'Ngân hàng',
    account: 'Số tài khoản',
    amount: 'Số tiền (không bắt buộc)',
    message: 'Nội dung chuyển khoản (không bắt buộc)',
    download: 'Tải PNG',
    sent: 'Nội dung sẽ gửi',
    check: 'Hãy quét thử bằng app ngân hàng của bạn để kiểm tra tên chủ tài khoản trước khi in hoặc chia sẻ.',
    errAccount: 'Số tài khoản này lạ quá, ngân hàng chắc cũng ngơ ngác. Chỉ gồm chữ và số, tối đa 19 ký tự nhé.',
    errAmount: 'Số tiền phải là số nguyên dương (đồng). Chuyển âm tiền thì ngân hàng chưa hỗ trợ đâu.',
    quipNoAmount: 'Mã không kèm số tiền: người quét tự nhập, tùy lòng hảo tâm.',
    quips: [
      [50_000, 'Tiền ly trà đá, gói xôi. Nhỏ thôi nhưng đòi được là vui rồi.'],
      [200_000, 'Vừa tiền trà sữa cả nhóm. Gửi mã này vào group là hết ai kêu quên.'],
      [1_000_000, 'Tiền ăn chung, tiền góp quỹ, có mã QR là khỏi đọc số tài khoản qua điện thoại.'],
      [10_000_000, 'Khoản này không nhỏ đâu. Kiểm tra kỹ tên người nhận trước khi chia sẻ nhé.'],
      [Infinity, 'Số tiền lớn rồi đấy. Quét thử thật kỹ, kiểm tra từng con số rồi hẵng gửi.'],
    ] as [number, string][],
    placeholderAccount: 'Ví dụ: 0123456789',
  },
  en: {
    bank: 'Bank',
    account: 'Account number',
    amount: 'Amount in VND (optional)',
    message: 'Transfer message (optional)',
    download: 'Download PNG',
    sent: 'Message that will be sent',
    check: 'Scan the code with your own banking app to confirm the account name before printing or sharing it.',
    errAccount: 'Even the bank would squint at that account number. Use letters and digits only, up to 19 characters.',
    errAmount: 'The amount must be a whole number of dong greater than 0. Negative transfers are not a thing yet.',
    quipNoAmount: 'No amount set: whoever scans it types the amount, generosity optional.',
    quips: [
      [50_000, 'Iced tea money. Small, but getting paid back always feels good.'],
      [200_000, 'Bubble tea for the team. Drop this in the group chat and nobody can "forget".'],
      [1_000_000, 'Shared dinner or team fund. No more reading account numbers over the phone.'],
      [10_000_000, 'That is a real amount. Double-check the recipient name before sharing.'],
      [Infinity, 'A big transfer. Test-scan it carefully and check every digit before sending.'],
    ] as [number, string][],
    placeholderAccount: 'e.g. 0123456789',
  },
};
export type VietQrStrings = (typeof S)['vi'];
