export const S = {
  vi: {
    g2n: 'Gross sang Net',
    n2g: 'Net sang Gross',
    gross: 'Lương Gross',
    net: 'Lương Net',
    dependents: 'Số người phụ thuộc',
    region: 'Vùng',
    insuranceSalary: 'Lương đóng bảo hiểm',
    insuranceHint: 'Bằng lương Gross',
    bhxh: 'BHXH (8%)',
    bhyt: 'BHYT (1,5%)',
    bhtn: 'BHTN (1%)',
    deductions: 'Giảm trừ gia cảnh',
    taxable: 'Thu nhập tính thuế',
    tax: 'Thuế TNCN',
    bracket: 'Bậc',
    asOf: 'Áp dụng quy định năm 2026 (cập nhật 10/2026). Kết quả mang tính tham khảo.',
    errInput: 'Nhập số tiền lớn hơn 0 và số người phụ thuộc là số nguyên không âm.',
    example: '30.000.000',
  },
  en: {
    g2n: 'Gross to Net',
    n2g: 'Net to Gross',
    gross: 'Gross salary',
    net: 'Net salary',
    dependents: 'Dependents',
    region: 'Region',
    insuranceSalary: 'Insurance salary',
    insuranceHint: 'Same as gross',
    bhxh: 'Social insurance (8%)',
    bhyt: 'Health insurance (1.5%)',
    bhtn: 'Unemployment insurance (1%)',
    deductions: 'Family deductions',
    taxable: 'Taxable income',
    tax: 'Personal income tax',
    bracket: 'Bracket',
    asOf: 'Uses Vietnam’s 2026 rules (updated 10/2026). Results are estimates.',
    errInput: 'Enter an amount above 0 and a whole number of dependents.',
    example: '30,000,000',
  },
};
export type SalaryStrings = (typeof S)['vi'];
