export const S = {
  vi: {
    g2n: 'Gross sang Net',
    n2g: 'Net sang Gross',
    gross: 'Lương Gross',
    net: 'Lương Net',
    dependents: 'Số người phụ thuộc',
    region: 'Vùng',
    insuranceSalary: 'Lương đóng bảo hiểm',
    insuranceHint: 'Bằng lương Gross',
    bhxh: 'BHXH (8%)',
    bhyt: 'BHYT (1,5%)',
    bhtn: 'BHTN (1%)',
    deductions: 'Giảm trừ gia cảnh',
    taxable: 'Thu nhập tính thuế',
    tax: 'Thuế TNCN',
    bracket: 'Bậc',
    portion: 'Thu nhập trong bậc',
    rate: 'Thuế suất',
    total: 'Tổng cộng',
    taxableFormula: 'Thu nhập tính thuế = {gross} (Gross) - {ins} (bảo hiểm) - {ded} (giảm trừ gia cảnh) = {taxable}',
    bracketNote: 'Thuế lũy tiến từng phần: mỗi bậc chỉ đánh thuế trên phần thu nhập nằm trong bậc đó, không phải trên toàn bộ thu nhập.',
    quips: [
      [0.000001, 'Thuế TNCN: 0 đồng. Nhà nước chưa cần tới bạn, cứ giữ tiền mua trà sữa.'],
      [0.02, 'Thuế đóng chưa nhiều, coi như góp tiền mua vài viên gạch lát vỉa hè.'],
      [0.05, 'Chúc mừng, bạn đã chính thức góp phần xây đường. Đi đường nhớ tự hào nhé.'],
      [0.1, 'Mỗi tháng góp hẳn một đoạn đường. Ổ gà nào còn thì không phải lỗi của bạn.'],
      [0.2, 'Kiếm 5 đồng thì nhà nước xin 1. Đối tác làm ăn trung thành nhất của bạn đây.'],
      [Infinity, 'Thu nhập cực khủng. Bộ Tài chính gửi lời cảm ơn chân thành, kèm cái cúi đầu.'],
    ] as [number, string][],
    asOf: 'Áp dụng quy định năm 2026 (cập nhật 10/2026). Kết quả mang tính tham khảo.',
    errInput: 'Nhập số tiền lớn hơn 0 và số người phụ thuộc là số nguyên không âm.',
    example: '30.000.000',
  },
  en: {
    g2n: 'Gross to Net',
    n2g: 'Net to Gross',
    gross: 'Gross salary',
    net: 'Net salary',
    dependents: 'Dependents',
    region: 'Region',
    insuranceSalary: 'Insurance salary',
    insuranceHint: 'Same as gross',
    bhxh: 'Social insurance (8%)',
    bhyt: 'Health insurance (1.5%)',
    bhtn: 'Unemployment insurance (1%)',
    deductions: 'Family deductions',
    taxable: 'Taxable income',
    tax: 'Personal income tax',
    bracket: 'Income bracket',
    portion: 'Income in this bracket',
    rate: 'Rate',
    total: 'Total',
    taxableFormula: 'Taxable income = {gross} (gross) - {ins} (insurance) - {ded} (family deductions) = {taxable}',
    bracketNote: 'Progressive tax: each rate applies only to the slice of income inside its bracket, not to the whole income.',
    quips: [
      [0.000001, 'Income tax: 0. The state does not need you yet. Spend it on bubble tea.'],
      [0.02, 'A modest tax bill. Think of it as buying a few pavement tiles for the city.'],
      [0.05, 'Congratulations, you are officially funding roads. Drive on them proudly.'],
      [0.1, 'You pay for a whole stretch of road each month. The potholes are not your fault.'],
      [0.2, 'For every 5 you earn, the state asks for 1. Your most loyal business partner.'],
      [Infinity, 'Serious income. The Ministry of Finance sends its heartfelt thanks and a bow.'],
    ] as [number, string][],
    asOf: 'Uses Vietnam’s 2026 rules (updated 10/2026). Results are estimates.',
    errInput: 'Enter an amount above 0 and a whole number of dependents.',
    example: '30,000,000',
  },
};
export type SalaryStrings = (typeof S)['vi'];
