export const S = {
  vi: {
    list: 'Danh sách thành viên (mỗi dòng một người)',
    byCount: 'Chia theo số đội',
    bySize: 'Chia theo số người mỗi đội',
    count: 'Số đội',
    size: 'Số người mỗi đội',
    make: 'Chia đội',
    team: 'Đội',
    copy: 'Sao chép',
    copied: 'Đã sao chép!',
    errEmpty: 'Danh sách đang trống, chưa có ai để chia đội. Thêm tên thành viên nhé.',
    errValue: 'Giá trị phải từ 1 đến số thành viên. Không thể chia đội cho người chưa đến.',
    quips: [
      'Đội đã chia xong, ngẫu nhiên 100%. Không ai được kêu "chia ăn gian".',
      'Xong! Muốn đổi đội thì đi mà thuyết phục cái máy.',
      'Đội hình đã có. Giờ chỉ còn thiếu cái tên đội thật kêu.',
      'Chia đội công bằng như chia bánh chưng ngày Tết.',
      'Đã chia đội. Ai thua nhớ bao cả nhóm chè nhé.',
    ],
    quipSolo: 'Có đội chỉ một người. Một mình một đội, gánh team đúng nghĩa đen.',
    example: 'Minh Anh\nGia Huy\nBảo Ngọc\nĐức Thịnh\nThu Trang\nQuốc Bảo\nHải Yến\nTuấn Kiệt\nLan Chi\nNhật Nam',
  },
  en: {
    list: 'Members (one per line)',
    byCount: 'By number of teams',
    bySize: 'By team size',
    count: 'Number of teams',
    size: 'People per team',
    make: 'Make teams',
    team: 'Team',
    copy: 'Copy',
    copied: 'Copied!',
    errEmpty: 'The list is empty, so there is nobody to split up. Add some members.',
    errValue: 'The value must be between 1 and the number of members. No-shows cannot join a team.',
    quips: [
      'Teams are set, 100% random. Nobody gets to cry "rigged".',
      'Done! Want to switch teams? Take it up with the algorithm.',
      'The lineup is ready. All you need now is a cool team name.',
      'Split as fairly as a pizza with a ruler.',
      'Teams made. Losing side buys the snacks.',
    ],
    quipSolo: 'One team has a single member. A one-person squad, carrying the team literally.',
    example: 'Olivia\nLiam\nAmelia\nNoah\nSophia\nLucas\nMia\nEthan\nChloe\nJack',
  },
};
export type TeamStrings = (typeof S)['vi'];
